=== saraalvarez122m/Sara-lvarez.-Lenguaje-de-Marcas.-DAW/TAREA 4. LENGUAJE DE MARCAS/Ejercicio 1/cifp.dtd
<!ELEMENT cifp (alumno | profesor)*>
<!ELEMENT alumno (nombre, apellidos, fecha_nacimiento?, email?, telefono?, direccion?, fecha_matricula, curso)>
<!ATTLIST alumno id ID #REQUIRED>
<!ELEMENT profesor (nombre, apellidos, fecha_nacimiento?, email?, telefono?, direccion?, fecha_incorporacion, departamento, asignatura*)>
<!ATTLIST profesor id ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT fecha_nacimiento (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT fecha_matricula (#PCDATA)>
<!ELEMENT curso (#PCDATA)>
<!ELEMENT fecha_incorporacion (#PCDATA)>
<!ELEMENT departamento (#PCDATA)>
<!ATTLIST departamento tipo (informatica|electricidad|automocion) #REQUIRED>
<!ELEMENT asignatura (nombre_asignatura, fecha_inicio?, fecha_fin?)>
<!ELEMENT nombre_asignatura (#PCDATA)>
<!ELEMENT fecha_inicio (#PCDATA)>
<!ELEMENT fecha_fin (#PCDATA)>
<!ATTLIST asignatura id ID #REQUIRED>
<!ATTLIST nombre_asignatura ciclo (DAM | DAW | ASIX | SMX | SEIA | ER | AUT) #REQUIRED>

=== saraalvarez122m/Sara-lvarez.-Lenguaje-de-Marcas.-DAW/TAREA 4. LENGUAJE DE MARCAS/Ejercicio 1/cifp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cifp SYSTEM "cifp.dtd">

<cifp>
  <alumno id="a1">
    <nombre>Juan</nombre>
    <apellidos>Garrido Ponts</apellidos>
    <fecha_nacimiento>1995-04-12</fecha_nacimiento>
    <email>juangarrido@gmail.com</email>
    <telefono>658142358</telefono>
    <direccion>Calle Ses savines,21</direccion>
    <fecha_matricula>2024-02-08</fecha_matricula>
    <curso>DAM</curso>
  </alumno>

  <profesor id="p1">
    <nombre>Maite</nombre>
    <apellidos>Cabrera</apellidos>
    <fecha_nacimiento>1996-01-25</fecha_nacimiento>
    <email>maitecm@gmail.com</email>
    <telefono>658963201</telefono>
    <direccion>Calle Ses dones,82</direccion>
    <fecha_incorporacion>2023-05-01</fecha_incorporacion>
    <departamento tipo="informatica">Sistemas</departamento>
    <asignatura id="asig1">
      <nombre_asignatura ciclo="DAM">Programacion</nombre_asignatura>
      <fecha_inicio>2024-02-01</fecha_inicio>
      <fecha_fin>2024-06-30</fecha_fin>
    </asignatura>
  </profesor>
</cifp>
