=== saraalvarez122m/Sara-lvarez.-Lenguaje-de-Marcas.-DAW/TAREA 4. LENGUAJE DE MARCAS/Ejercicio 1.3_1.4/cifp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="cifp">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        
        <xs:element name="alumno">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="apellidos" type="xs:string"/>
              <xs:element name="fecha_nacimiento" type="xs:string" minOccurs="0"/>
              <xs:element name="email" type="xs:string" minOccurs="0"/>
              <xs:element name="telefono" type="xs:string" minOccurs="0"/>
              <xs:element name="direccion" type="xs:string" minOccurs="0"/>
              <xs:element name="fecha_matricula" type="xs:string"/>
              <xs:element name="curso">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="DAM"/><xs:enumeration value="DAW"/>
                    <xs:enumeration value="ASIX"/><xs:enumeration value="SMX"/>
                    <xs:enumeration value="SEIA"/><xs:enumeration value="ER"/><xs:enumeration value="AUT"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:integer" use="required"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="profesor">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="apellidos" type="xs:string"/>
              <xs:element name="fecha_nacimiento" type="xs:string" minOccurs="0"/>
              <xs:element name="email" type="xs:string" minOccurs="0"/>
              <xs:element name="telefono" type="xs:string" minOccurs="0"/>
              <xs:element name="direccion" type="xs:string" minOccurs="0"/>
              <xs:element name="fecha_incorporacion" type="xs:string"/>
              <xs:element name="departamento">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="informatica"/>
                    <xs:enumeration value="electricidad"/>
                    <xs:enumeration value="automocion"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="asignatura" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="nombre_asignatura">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="ciclo" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="fecha_inicio" type="xs:string" minOccurs="0"/>
                    <xs:element name="fecha_fin" type="xs:string" minOccurs="0"/>
                  </xs:sequence>
                  <xs:attribute name="id_asignatura" type="xs:integer" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:integer" use="required"/>
          </xs:complexType>
        </xs:element>

      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== saraalvarez122m/Sara-lvarez.-Lenguaje-de-Marcas.-DAW/cifp_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<cifp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xsi:noNamespaceSchemaLocation="cifp.xsd">
    
    <alumno id="01">
        <nombre>Juan</nombre>
        <apellidos>Garrido Ponts</apellidos>
        <fecha_nacimiento>1995-05-12</fecha_nacimiento>
        <email>joangarrido@gmail.com</email>
        <telefono>657257485</telefono>
        <direccion>Calle Ledesmas, 21</direccion>
        <fecha_matricula>2025-11-02</fecha_matricula>
        <curso>DAW</curso>
    </alumno>

    <profesor id="02">
        <nombre>Maite</nombre>
        <apellidos>Cabrera Mustafa</apellidos>
        <fecha_incorporacion>2025-08-25</fecha_incorporacion>
        <departamento>informatica</departamento>
        <asignatura id_asignatura="03">
            <nombre_asignatura ciclo="DAM">Lenguaje Marcas</nombre_asignatura>
            <fecha_inicio>2024-11-11</fecha_inicio>
            <fecha_fin>2025-05-23</fecha_fin>
        </asignatura>
    </profesor>
</cifp>
